'use client';
import {useMemo,useState} from 'react';
import {Search,HeartPulse,ChevronRight,Play,ShieldAlert,RotateCcw,BookOpen,CheckCircle2,X,ExternalLink,Leaf,Activity,Utensils,House,SunMedium} from 'lucide-react';
import {diseases,Category,Item} from '../data';
const cats:({id:'all'|Category;label:string;icon:any})[]=[{id:'all',label:'All',icon:Leaf},{id:'Yoga',label:'Yoga',icon:SunMedium},{id:'Exercise',label:'Exercise',icon:Activity},{id:'Diet',label:'Diet',icon:Utensils},{id:'Home care',label:'Home care',icon:House},{id:'Habits',label:'Habits',icon:CheckCircle2}];
export default function Home(){
 const [query,setQuery]=useState(''); const [selected,setSelected]=useState<string[]>([]); const [tab,setTab]=useState<'all'|Category>('all'); const [detail,setDetail]=useState<Item|null>(null); const [showSources,setShowSources]=useState(false);
 const results=useMemo(()=>diseases.filter(d=>(d.name+' '+d.aliases.join(' ')).toLowerCase().includes(query.trim().toLowerCase())),[query]);
 const chosen=useMemo(()=>diseases.filter(d=>selected.includes(d.id)),[selected]);
 const items=useMemo(()=>{const all=chosen.flatMap(d=>d.items);const seen=new Set<string>();return all.filter(x=>{if(tab!=='all'&&x.category!==tab)return false;if(seen.has(x.title))return false;seen.add(x.title);return true})},[chosen,tab]);
 const toggle=(id:string)=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
 const reset=()=>{setSelected([]);setQuery('');setTab('all');setDetail(null)};
 return <main>
  <header><div className="brand"><div className="logo"><HeartPulse size={25}/></div><div><b>WellPath</b><span>Personal wellness guide</span></div></div><button className="reset" onClick={reset}><RotateCcw size={16}/> Reset</button></header>
  <section className="hero"><div><p className="eyebrow">YOUR WELLNESS COMPANION</p><h1>Build a safer wellness plan around <em>your conditions.</em></h1><p className="sub">Choose one or more conditions. WellPath organizes general yoga, exercise, food, home-care and habit information while highlighting precautions and evidence sources.</p></div><div className="hero-card"><ShieldAlert/><b>Education, not diagnosis</b><p>Recommendations are general and do not replace a clinician, prescription, diagnosis or emergency care.</p><div className="mini-stat"><span>{diseases.length}</span><small>conditions in this version</small></div></div></section>
  <section className="selector"><div className="selector-title"><div><p className="eyebrow">STEP 1</p><h2>Choose your conditions</h2></div><span>{selected.length} selected</span></div><div className="search"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search a disease or condition…"/><kbd>⌕</kbd></div><div className="chips">{results.length?results.map(d=><button key={d.id} className={selected.includes(d.id)?'chip active':'chip'} onClick={()=>toggle(d.id)}>{d.name}{selected.includes(d.id)&&' ✓'}</button>):<div className="no-results">No matching condition. Try another term.</div>}</div>{selected.length>0&&<div className="selected"><b>Selected:</b>{chosen.map(d=><button key={d.id} onClick={()=>toggle(d.id)}>{d.name}<X size={13}/></button>)}</div>}</section>
  {selected.length>0?<section className="plan"><div className="plan-head"><div><p className="eyebrow">STEP 2 · PERSONALIZED VIEW</p><h2>Your wellness ideas</h2><p className="muted">{chosen.map(d=>d.name).join(' + ')}</p></div><div className="tabs">{cats.map(c=>{const I=c.icon;return <button key={c.id} className={tab===c.id?'on':''} onClick={()=>setTab(c.id)}><I size={14}/>{c.label}</button>})}</div></div>
   <div className="safety-grid"><div className="notice"><ShieldAlert size={19}/><div><b>Safety first</b><span>Multiple conditions can change what is appropriate. Start gently and check with a healthcare professional before a new exercise or diet plan.</span></div></div><div className="summary"><span>{items.length}</span><div><b>Ideas shown</b><small>filtered for your selection</small></div></div></div>
   <div className="redflags"><div className="red-title"><ShieldAlert size={18}/> When to seek medical care</div><div className="red-list">{Array.from(new Set(chosen.flatMap(d=>d.redFlags))).slice(0,6).map((x,i)=><span key={i}>• {x}</span>)}</div></div>
   <div className="grid">{items.map(x=><Card key={x.id} item={x} onOpen={()=>setDetail(x)}/>)}</div>
   <button className="sources-toggle" onClick={()=>setShowSources(v=>!v)}><BookOpen size={16}/>{showSources?'Hide':'Show'} evidence sources <ChevronRight size={15}/></button>
   {showSources&&<div className="sources"><p>Sources are included to help you verify general wellness information. They are not endorsements of individual videos.</p>{Array.from(new Map<string,{label:string;url:string}>(items.map(i=>[i.source.url,i.source])).values()).map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer"><BookOpen size={15}/><span>{s.label}</span><ExternalLink size={13}/></a>)}</div>}
  </section>:<section className="empty"><div className="empty-icon">✦</div><h2>Start by selecting a condition</h2><p>Choose one or more conditions above. Your wellness dashboard will appear here.</p><div className="feature-row"><span>🧘 Yoga</span><span>🏃 Exercise</span><span>🥗 Diet</span><span>🏠 Home care</span><span>😴 Habits</span></div></section>}
  <footer><b>WellPath</b> is an educational wellness tool. It does not diagnose, treat, cure or prevent disease. Information can be incomplete or unsuitable for an individual. In an emergency, contact local emergency services.</footer>
  {detail&&<div className="modal-backdrop" onClick={()=>setDetail(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setDetail(null)}><X/></button><div className="modal-photo" style={{backgroundImage:`url(${detail.image})`}}><span>{detail.category}</span></div><div className="modal-body"><p className="eyebrow">RECOMMENDATION</p><h2>{detail.title}</h2><p className="lead">{detail.description}</p><h3>How to approach it</h3><p>{detail.how}</p><div className="modal-caution"><ShieldAlert size={17}/><div><b>Precaution</b><p>{detail.caution}</p></div></div><div className="tag-row">{detail.tags.map(t=><span key={t}>#{t}</span>)}</div><div className="modal-actions"><a href={detail.video} target="_blank" rel="noreferrer"><Play size={16}/> Find video demonstrations</a><a className="source-link" href={detail.source.url} target="_blank" rel="noreferrer"><BookOpen size={16}/> {detail.source.label}</a></div></div></div></div>}
 </main>
}
function Card({item,onOpen}:{item:Item;onOpen:()=>void}){return <article className="card"><div className="photo" style={{backgroundImage:`url(${item.image})`}}><span>{item.category}</span></div><div className="card-body"><h3>{item.title}</h3><p>{item.description}</p><button className="learn" onClick={onOpen}>View instructions <ChevronRight size={15}/></button><div className="caution"><b>⚠ Precaution</b><span>{item.caution}</span></div><div className="card-source"><BookOpen size={13}/>{item.source.label}</div></div></article>}
