'use client';
import {useMemo,useState} from 'react';
import {conditions,systems,Condition} from '../data/conditions';
import './globals.css';

type Tab='home'|'diseases'|'plan'|'track'|'doctors'|'safety';
type Log={date:string;weight:string;bp:string;sleep:string;water:string;mood:string;steps:string};
const LS='wellpath-ultimate-v3';
const tips=[['Movement','10–30 minutes of comfortable activity, adjusted to your ability.'],['Food','Build meals around vegetables/fruit, a suitable protein, whole grains or other staple, and water.'],['Sleep','Keep a consistent sleep/wake schedule and create a wind-down routine.'],['Hydration','Use thirst and clinician guidance; fluid limits apply to some conditions.'],['Stress','Use gentle breathing, grounding or a short calming routine.'],['Follow-up','Keep prescribed medicines, tests and appointments on schedule.']];
const emergency=['Chest pain/pressure with severe symptoms','Severe breathing difficulty or blue/grey lips','Sudden face/arm weakness or speech trouble','Fainting, seizure or new severe confusion','Uncontrolled heavy bleeding','Sudden worst-ever headache','Thoughts of self-harm or inability to stay safe'];
function load(){if(typeof window==='undefined')return {selected:[] as string[],goals:[] as string[],logs:[] as Log[],meds:[] as string[],allergies:[] as string[]};try{return JSON.parse(localStorage.getItem(LS)||'{}')}catch{return {}}}
export default function Home(){
 const initial=load();
 const [tab,setTab]=useState<Tab>('home'); const [q,setQ]=useState(''); const [system,setSystem]=useState('All'); const [selected,setSelected]=useState<string[]>(initial.selected||[]); const [detail,setDetail]=useState<Condition|null>(null); const [whoQuery,setWhoQuery]=useState(''); const [whoResults,setWhoResults]=useState<any[]>([]); const [whoLoading,setWhoLoading]=useState(false); const [whoMsg,setWhoMsg]=useState(''); const [goals,setGoals]=useState<string[]>(initial.goals||[]); const [logs,setLogs]=useState<Log[]>(initial.logs||[]); const [meds,setMeds]=useState<string[]>(initial.meds||[]); const [allergies,setAllergies]=useState<string[]>(initial.allergies||[]); const [profile,setProfile]=useState(initial.profile||{age:'',sex:'',pregnancy:'',activity:'Beginner'}); const [doctorAddress,setDoctorAddress]=useState(''); const [doctorPin,setDoctorPin]=useState(''); const [doctorResults,setDoctorResults]=useState<any[]>([]); const [doctorSpecialties,setDoctorSpecialties]=useState<string[]>([]); const [doctorLocation,setDoctorLocation]=useState(''); const [doctorLoading,setDoctorLoading]=useState(false); const [doctorMsg,setDoctorMsg]=useState(''); const [newMed,setNewMed]=useState(''); const [newAllergy,setNewAllergy]=useState(''); const [showProfile,setShowProfile]=useState(false);
 const save=(next:any)=>{if(typeof window!=='undefined')localStorage.setItem(LS,JSON.stringify(next))};
 const choose=(id:string)=>{const n=selected.includes(id)?selected.filter(x=>x!==id):[...selected,id];setSelected(n);save({selected:n,goals,logs,meds,allergies})};
 const filtered=useMemo(()=>conditions.filter(c=>(system==='All'||c.system===system)&&(!q||(c.name+' '+c.name+' '+c.system).toLowerCase().includes(q.toLowerCase()))),[q,system]);
 const chosen=conditions.filter(c=>selected.includes(c.id));
 const score=Math.min(100,55+selected.length*7+(goals.length?10:0));
 const addGoal=(x:string)=>{const n=goals.includes(x)?goals.filter(g=>g!==x):[...goals,x];setGoals(n);save({selected,goals:n,logs,meds,allergies})};
 const addMed=()=>{if(!newMed.trim())return;const n=[...meds,newMed.trim()];setMeds(n);setNewMed('');save({selected,goals,logs,meds:n,allergies})};
 const addAllergy=()=>{if(!newAllergy.trim())return;const n=[...allergies,newAllergy.trim()];setAllergies(n);setNewAllergy('');save({selected,goals,logs,meds,allergies:n})};
 const reset=()=>{localStorage.removeItem(LS);location.reload()};
 const whoSearch=async()=>{if(!whoQuery.trim())return;setWhoLoading(true);setWhoMsg('');try{const r=await fetch('/api/icd/search?q='+encodeURIComponent(whoQuery.trim()));const d=await r.json();if(!r.ok)throw new Error(d.error||'WHO search failed');setWhoResults(d.results||[]);if(!(d.results||[]).length)setWhoMsg('No matching ICD-11 results found.')}catch(e:any){setWhoMsg(e.message||'WHO search unavailable.')}finally{setWhoLoading(false)}};
 const findDoctors=async()=>{if(!doctorAddress.trim()||!/^\d{6}$/.test(doctorPin)){setDoctorMsg('Enter your locality/address and a valid 6-digit Indian PIN code.');return} if(!chosen.length){setDoctorMsg('Select at least one condition first so WellPath can suggest relevant specialties.');return} setDoctorLoading(true);setDoctorMsg('');setDoctorResults([]);try{const r=await fetch('/api/doctors/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({address:doctorAddress,pin:doctorPin,diseases:chosen.map(c=>c.name)})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Doctor search failed');setDoctorResults(d.doctors||[]);setDoctorSpecialties(d.specialties||[]);setDoctorLocation(d.location||'');if(!(d.doctors||[]).length)setDoctorMsg('No nearby providers were returned. Try a larger nearby locality or landmark.')}catch(e:any){setDoctorMsg(e.message||'Doctor search unavailable.')}finally{setDoctorLoading(false)}};
 return <div className="app">
  <header className="top"><div className="brand"><div className="logo">♥</div><div><b>WellPath</b><small>Ultimate wellness companion</small></div></div><div className="top-actions"><button onClick={()=>setShowProfile(true)}>Profile</button><button onClick={reset}>Reset</button></div></header>
  <div className="hero"><div><div className="eyebrow">WELLNESS • EDUCATION • SAFETY</div><h1>Your health, organized around <em>your whole life.</em></h1><p>Explore conditions, build a personalized daily routine, track progress and find safety information. WellPath is educational and does not diagnose or prescribe.</p><div className="hero-actions"><button className="primary" onClick={()=>setTab('diseases')}>Explore conditions</button><button className="secondary" onClick={()=>setTab('plan')}>Build my plan</button></div></div><div className="score"><span>Plan readiness</span><strong>{score}</strong><small>/100</small><div className="bar"><i style={{width:`${score}%`}}/></div><p>{selected.length?`${selected.length} condition${selected.length>1?'s':''} selected`:'Select conditions to personalize'}</p></div></div>
  <nav className="nav">{([['home','Home'],['diseases','Conditions'],['plan','Daily plan'],['track','Progress'],['doctors','Find doctors'],['safety','Safety']] as [Tab,string][]).map(([id,label])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}>{label}</button>)}</nav>
  {tab==='home'&&<HomeTab chosen={chosen} selected={selected} choose={choose} setTab={setTab} addGoal={addGoal} goals={goals}/>} 
  {tab==='diseases'&&<section className="section"><div className="section-head"><div><div className="eyebrow">GLOBAL CONDITION LIBRARY</div><h2>Conditions & diseases</h2><p>Search the local starter library, or use the live WHO ICD-11 2026 search below when configured.</p></div><a className="source" href="https://icd.who.int/browse/2026-01/mms/en" target="_blank">Open WHO ICD-11 ↗</a></div><div className="search"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search disease or body system…"/><select aria-label="Filter by body system" value={system} onChange={e=>setSystem(e.target.value)}>{systems.map(s=><option key={s}>{s}</option>)}</select></div><div className="who-box"><div><div className="eyebrow">WHO ICD-11 2026 SEARCH</div><h3>Search the global disease classification</h3><p>When configured, this searches the WHO ICD-11 Foundation. The local catalog remains available without an API key.</p></div><div className="inline"><input aria-label="Search WHO ICD-11" value={whoQuery} onChange={e=>setWhoQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')whoSearch()}} placeholder="e.g. tuberculosis, migraine, lupus"/><button onClick={whoSearch} disabled={whoLoading}>{whoLoading?'Searching…':'Search WHO'}</button></div>{whoMsg&&<p className="muted">{whoMsg}</p>}{whoResults.length>0&&<div className="who-results">{whoResults.map((r:any)=><button className="who-result" key={r.uri} onClick={()=>setWhoMsg(`${r.title}${r.code?` · ICD-11 ${r.code}`:''}`)}><b>{r.title}</b><span>{r.code||'ICD entity'}{r.chapter?` · Chapter ${r.chapter}`:''}</span></button>)}</div>}</div><div className="count">Showing {filtered.length} conditions in the starter catalog · {selected.length} selected</div><div className="condition-grid">{filtered.map(c=><article className={selected.includes(c.id)?'condition selected':'condition'} key={c.id}><div className="condition-top"><span className="pill">{c.system}</span><button onClick={()=>choose(c.id)}>{selected.includes(c.id)?'✓ Selected':'Select'}</button></div><h3>{c.name}</h3><p>{c.summary}</p><div className="mini-flags">⚠ {c.flags[0]}</div><div className="card-actions"><button onClick={()=>setDetail(c)}>View details</button><button onClick={()=>choose(c.id)}>{selected.includes(c.id)?'Remove':'Add to plan'}</button></div></article>)}</div></section>}
  {tab==='plan'&&<Plan chosen={chosen} goals={goals} addGoal={addGoal} profile={profile}/>}
  {tab==='doctors'&&<Doctors chosen={chosen} address={doctorAddress} setAddress={setDoctorAddress} pin={doctorPin} setPin={setDoctorPin} loading={doctorLoading} msg={doctorMsg} results={doctorResults} specialties={doctorSpecialties} location={doctorLocation} find={findDoctors}/>} 
  {tab==='track'&&<Tracker logs={logs} setLogs={n=>{setLogs(n);save({selected,goals,logs:n,meds,allergies})}} meds={meds} setMeds={n=>{setMeds(n);save({selected,goals,logs,meds:n,allergies})}} newMed={newMed} setNewMed={setNewMed} addMed={addMed} allergies={allergies} setAllergies={n=>{setAllergies(n);save({selected,goals,logs,meds,allergies:n})}} newAllergy={newAllergy} setNewAllergy={setNewAllergy} addAllergy={addAllergy}/>} 
  {tab==='safety'&&<Safety chosen={chosen}/>} 
  <footer><b>WellPath Ultimate V5</b> • Educational wellness support, not diagnosis or treatment. For emergencies, contact your local emergency service. Content should be clinically reviewed before use as a medical product.</footer>
  {detail&&<div className="overlay" onClick={()=>setDetail(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setDetail(null)}>×</button><span className="pill">{detail.system}</span><h2>{detail.name}</h2><p>{detail.summary}</p><h3>Personalized wellness themes</h3><ul>{detail.tips.map(t=><li key={t}>{t}</li>)}</ul><div className="danger"><b>When to seek urgent care</b><p>{detail.flags[0]}</p></div><div className="modal-actions"><button className="primary" onClick={()=>{choose(detail.id);setDetail(null);setTab('plan')}}>Add to my plan</button><a className="secondary" href="https://icd.who.int/browse/2026-01/mms/en" target="_blank">WHO reference</a></div></div></div>}
  {showProfile&&<div className="overlay" onClick={()=>setShowProfile(false)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setShowProfile(false)}>×</button><div className="eyebrow">YOUR PROFILE</div><h2>Personalize safely</h2><p>These details stay in your browser in this version and are used only to tailor generic planning language.</p><label>Age<input value={profile.age} onChange={e=>setProfile({...profile,age:e.target.value})}/></label><label>Sex / context<input value={profile.sex} onChange={e=>setProfile({...profile,sex:e.target.value})}/></label><label>Pregnancy status if relevant<input value={profile.pregnancy} onChange={e=>setProfile({...profile,pregnancy:e.target.value})}/></label><label>Activity level<select value={profile.activity} onChange={e=>setProfile({...profile,activity:e.target.value})}><option>Beginner</option><option>Moderate</option><option>Active</option></select></label><button className="primary" onClick={()=>{save({selected,goals,logs,meds,allergies,profile});setShowProfile(false)}}>Save locally</button></div></div>}
 </div>
}
function Doctors({chosen,address,setAddress,pin,setPin,loading,msg,results,specialties,location,find}:{chosen:Condition[];address:string;setAddress:(x:string)=>void;pin:string;setPin:(x:string)=>void;loading:boolean;msg:string;results:any[];specialties:string[];location:string;find:()=>void}){return <section className="section"><div className="section-head"><div><div className="eyebrow">LOCAL CARE FINDER</div><h2>Find doctors near you</h2><p>Enter the patient’s locality/address and 6-digit PIN. WellPath uses the selected conditions to suggest relevant specialties and searches nearby healthcare providers.</p></div></div><div className="doctor-search panel"><div className="doctor-note"><b>Selected conditions</b><span>{chosen.length?chosen.map(c=>c.name).join(', '):'None selected yet'}</span></div><div className="fields"><label>Address / locality<input aria-label="Patient address or locality" value={address} onChange={e=>setAddress(e.target.value)} placeholder="House/locality, town or nearby landmark"/></label><label>PIN code<input aria-label="Indian PIN code" inputMode="numeric" maxLength={6} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="e.g. 767001"/></label></div><button className="primary" onClick={find} disabled={loading}>{loading?'Finding nearby doctors…':'Find doctors near me'}</button><p className="privacy">Location is used for this search and is not saved by WellPath. The search is processed through the configured maps provider.</p></div>{msg&&<div className="notice">{msg}</div>}{specialties.length>0&&<div className="specialty-row"><b>Suggested specialties:</b>{specialties.map(s=><span className="pill" key={s}>{s}</span>)}</div>}{location&&<p className="muted">Search area: {location}</p>}<div className="doctor-grid">{results.map(d=><article className="doctor-card" key={d.id}><div className="doctor-card-top"><div><span className="pill">{d.specialty}</span><h3>{d.name}</h3></div>{d.rating&&<span className="rating">★ {d.rating} <small>({d.reviews})</small></span>}</div><p>{d.address||'Address not provided'}</p>{d.phone&&<p>☎ {d.phone}</p>}<div className="card-actions">{d.maps&&<a className="primary linkbtn" href={d.maps} target="_blank" rel="noreferrer">View location</a>}{d.website&&<a className="secondary" href={d.website} target="_blank" rel="noreferrer">Website</a>}</div><small className="verify">Verify specialty, consultation hours and availability before visiting.</small></article>)}</div><div className="notice">Doctor listings come from the configured maps/place directory and can be incomplete or outdated. WellPath does not endorse or rank clinicians and does not confirm medical credentials, fees, appointment availability, or treatment quality.</div></section>}

function HomeTab({chosen,selected,choose,setTab,addGoal,goals}:{chosen:Condition[];selected:string[];choose:(x:string)=>void;setTab:(x:Tab)=>void;addGoal:(x:string)=>void;goals:string[]}){return <section className="section"><div className="section-head"><div><div className="eyebrow">YOUR DASHBOARD</div><h2>Start with what matters today</h2><p>{chosen.length?`Your plan is built around ${chosen.map(x=>x.name).join(', ')}.`:'Select one or more conditions to unlock personalized planning.'}</p></div></div>{!chosen.length?<div className="empty"><div className="empty-icon">+</div><h3>Select your conditions</h3><p>Use the Conditions tab to choose health topics that matter to you.</p><button className="primary" onClick={()=>setTab('diseases')}>Open condition library</button></div>:<><div className="quick-grid">{tips.map(([a,b])=><button className="quick" key={a} onClick={()=>setTab('plan')}><span>{a}</span><b>{b}</b></button>)}</div><div className="section-head compact"><div><h3>Suggested goals</h3><p>Choose one or two rather than trying everything at once.</p></div></div><div className="goal-grid">{['Walk 20 minutes','Keep a regular sleep time','Drink fluids appropriately','Eat one more vegetable serving','Do a 5-minute relaxation routine','Prepare questions for my clinician'].map(g=><button className={goals.includes(g)?'goal on':'goal'} onClick={()=>addGoal(g)} key={g}>{goals.includes(g)?'✓ ':''}{g}</button>)}</div></>}</section>}
function Plan({chosen,goals,addGoal,profile}:{chosen:Condition[];goals:string[];addGoal:(x:string)=>void;profile:any}){const combined=Array.from(new Set(chosen.flatMap(c=>c.tips)));return <section className="section"><div className="section-head"><div><div className="eyebrow">DAILY PLAN</div><h2>A gentle, realistic day</h2><p>Designed as education. Adapt it to your clinician’s instructions and ability.</p></div><span className="pill">{profile.activity}</span></div><div className="timeline">{[['Morning','Hydration + prescribed routine','Start the day with your usual medications as prescribed, breakfast if appropriate and a short mobility/walk routine.'],['Midday','Balanced meal + movement','Choose a balanced meal and add comfortable movement. Stop for concerning symptoms.'],['Afternoon','Reset','Take a 5-minute breathing/grounding break and review your hydration needs.'],['Evening','Wind down','Keep dinner appropriate for your condition and create a low-stimulation sleep routine.'],['Night','Sleep','Aim for a consistent sleep/wake schedule; seek assessment for persistent sleep problems.']].map(([a,b,c])=><div className="time" key={a}><span>{a}</span><div><h3>{b}</h3><p>{c}</p></div></div>)}</div><div className="two"><div className="panel"><h3>Condition-specific themes</h3>{combined.length?combined.map(x=><label className="check" key={x}><input type="checkbox"/> {x}</label>):<p>Select conditions to personalize.</p>}</div><div className="panel"><h3>Your goals</h3>{goals.length?goals.map(x=><button className="goal on" key={x} onClick={()=>addGoal(x)}>✓ {x}</button>):<p>No goals selected yet.</p>}</div></div><div className="notice">⚠ Multiple conditions, pregnancy, allergies, kidney/heart disease, medicines and recent procedures can change what is safe. This app intentionally avoids giving medication doses or diagnosis.</div></section>}
function Tracker({logs,setLogs,meds,setMeds,newMed,setNewMed,addMed,allergies,setAllergies,newAllergy,setNewAllergy,addAllergy}:{logs:Log[];setLogs:(n:Log[])=>void;meds:string[];setMeds:(n:string[])=>void;newMed:string;setNewMed:(x:string)=>void;addMed:()=>void;allergies:string[];setAllergies:(n:string[])=>void;newAllergy:string;setNewAllergy:(x:string)=>void;addAllergy:()=>void}){const [form,setForm]=useState<Log>({date:new Date().toISOString().slice(0,10),weight:'',bp:'',sleep:'',water:'',mood:'',steps:''});const add=()=>{if(!form.date)return;setLogs([form,...logs].slice(0,30));setForm({...form,date:new Date().toISOString().slice(0,10),weight:'',bp:'',sleep:'',water:'',mood:'',steps:''})};return <section className="section"><div className="section-head"><div><div className="eyebrow">PROGRESS & RECORDS</div><h2>Track trends, not perfection</h2><p>Stored locally in this browser. Do not use this as a substitute for clinical records.</p></div></div><div className="tracker-grid"><div className="panel"><h3>Daily log</h3><div className="fields">{[['weight','Weight'],['bp','Blood pressure'],['sleep','Sleep hours'],['water','Fluids'],['mood','Mood'],['steps','Steps']].map(([k,l])=><label key={k}>{l}<input value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}</div><button className="primary" onClick={add}>Save today</button></div><div className="panel"><h3>Recent entries</h3>{logs.length?logs.slice(0,8).map(x=><div className="log" key={x.date+x.weight}><b>{x.date}</b><span>{x.bp||'—'} · {x.sleep||'—'}h sleep · {x.steps||'—'} steps</span></div>):<p>No entries yet.</p>}</div></div><div className="two"><div className="panel"><h3>Medication list</h3><div className="inline"><input value={newMed} onChange={e=>setNewMed(e.target.value)} placeholder="Medicine name (no dose advice)"/><button onClick={addMed}>Add</button></div>{meds.map(x=><div className="tag" key={x}>{x}<button onClick={()=>setMeds(meds.filter(m=>m!==x))}>×</button></div>)}</div><div className="panel"><h3>Allergies / sensitivities</h3><div className="inline"><input value={newAllergy} onChange={e=>setNewAllergy(e.target.value)} placeholder="e.g. penicillin, peanuts"/><button onClick={addAllergy}>Add</button></div>{allergies.map(x=><div className="tag" key={x}>{x}<button onClick={()=>setAllergies(allergies.filter(m=>m!==x))}>×</button></div>)}</div></div></section>}
function Safety({chosen}:{chosen:Condition[]}){const flags=Array.from(new Set([...emergency,...chosen.flatMap(c=>c.flags)]));return <section className="section"><div className="section-head"><div><div className="eyebrow">SAFETY CENTER</div><h2>Know when to get help</h2><p>These are broad safety signals, not a diagnosis. If you think you are having an emergency, use your local emergency service.</p></div></div><div className="danger-grid">{flags.map((x,i)=><article className="danger-card" key={x}><span>!</span><div><b>{i<7?'Urgent warning':'Condition-specific warning'}</b><p>{x}</p></div></article>)}</div><div className="panel"><h3>Appointment preparation</h3><div className="checklist">{['What symptoms started and when?','What makes them better or worse?','Current medicines and supplements','Known allergies','Home measurements or logs','Questions about tests or treatment','Recent hospital/urgent-care visits'].map(x=><label key={x}><input type="checkbox"/> {x}</label>)}</div></div></section>}
