export type Category = 'Yoga'|'Exercise'|'Diet'|'Home care'|'Habits';
export type Item = {title:string; category:Category; description:string; how:string; caution:string; image:string; video:string; tags:string[]};
export type Disease = {id:string; name:string; aliases:string[]; summary:string; caution:string; items:Item[]};

const img=(q:string)=>`https://images.unsplash.com/photo-${q}?auto=format&fit=crop&w=900&q=80`;

export const diseases:Disease[]=[
{id:'diabetes',name:'Type 2 Diabetes',aliases:['sugar','high blood sugar','diabetes mellitus'],summary:'Supportive lifestyle guidance for people managing type 2 diabetes. It does not replace prescribed treatment.',caution:'Do not stop diabetes medicines or insulin based on this app. If you use glucose-lowering medicines, ask your clinician about exercise and low-blood-sugar precautions.',items:[
{title:'Brisk walking',category:'Exercise',description:'A practical aerobic activity that can support overall fitness and blood-glucose management.',how:'Start with 10–15 minutes at a comfortable pace and build gradually toward regular activity as tolerated.',caution:'Check with your clinician if you have foot problems, chest pain, severe breathlessness, or exercise restrictions.',image:img('1552674605-db6ffd4facb5'),video:'https://www.youtube.com/results?search_query=diabetes+safe+walking+exercise',tags:['walking','aerobic']},
{title:'Gentle yoga',category:'Yoga',description:'Gentle movement, breathing and flexibility work can complement an active lifestyle.',how:'Use beginner-level poses, move slowly and stop if you feel dizzy or unwell.',caution:'Avoid extreme poses and do not use yoga as a substitute for glucose monitoring or medical treatment.',image:img('1544367567-0f2fcb009e0b'),video:'https://www.youtube.com/results?search_query=gentle+yoga+for+diabetes',tags:['beginner','mobility']},
{title:'Balanced high-fiber meals',category:'Diet',description:'Prioritize vegetables, pulses, whole grains and other minimally processed foods while keeping portions appropriate.',how:'Build meals around vegetables and a protein source; choose high-fiber carbohydrates and limit sugary drinks.',caution:'Individual carbohydrate needs vary, especially with diabetes medicines. A dietitian can personalize portions.',image:img('1498837167922-ddd27525d352'),video:'https://www.youtube.com/results?search_query=diabetes+healthy+plate',tags:['fiber','balanced']},
{title:'Consistent sleep routine',category:'Habits',description:'Regular sleep timing can support overall metabolic and mental wellbeing.',how:'Keep a consistent bedtime and wake time, reduce late-night screens, and aim for adequate sleep.',caution:'Persistent loud snoring, witnessed pauses in breathing, or severe daytime sleepiness should be discussed with a clinician.',image:img('1511295742362-92c96b0f9b7d'),video:'https://www.youtube.com/results?search_query=sleep+hygiene+tips',tags:['sleep','routine']}
]},
{id:'hypertension',name:'High Blood Pressure',aliases:['bp','high bp','hypertension'],summary:'Lifestyle measures that may support cardiovascular health alongside prescribed care.',caution:'High blood pressure can be serious without symptoms. Continue prescribed medicines and seek urgent care for severe symptoms such as chest pain, severe breathlessness, weakness, or neurological changes.',items:[
{title:'Moderate walking',category:'Exercise',description:'Regular moderate aerobic activity is a common component of heart-healthy lifestyle plans.',how:'Begin gradually and work toward regular weekly activity according to your clinician’s advice.',caution:'Stop and seek medical advice for chest pain, fainting, unusual severe breathlessness, or concerning symptoms.',image:img('1551632811-561732d1e306'),video:'https://www.youtube.com/results?search_query=walking+exercise+high+blood+pressure',tags:['walking','cardio']},
{title:'Slow breathing practice',category:'Yoga',description:'Gentle slow breathing can be used as a relaxation practice.',how:'Sit comfortably, breathe gently without straining, and practice for a few minutes.',caution:'Do not force breath-holding or hyperventilation. Stop if light-headed.',image:img('1506126613408-eca07ce68773'),video:'https://www.youtube.com/results?search_query=slow+breathing+relaxation',tags:['breathing','relaxation']},
{title:'Lower-sodium eating pattern',category:'Diet',description:'Emphasize vegetables, fruit, pulses, whole grains and minimally processed foods, while limiting excess sodium.',how:'Taste food before adding salt and check packaged-food labels for sodium.',caution:'People with kidney, heart or other conditions may have individualized fluid/electrolyte advice.',image:img('1547592180-85f173990554'),video:'https://www.youtube.com/results?search_query=low+sodium+diet+tips',tags:['sodium','heart healthy']},
{title:'Avoid tobacco and limit alcohol',category:'Habits',description:'Avoiding tobacco and keeping alcohol low or avoiding it can support cardiovascular health.',how:'Use practical supports such as a quit plan, social support, and professional help if needed.',caution:'If you drink heavily, seek medical advice before stopping suddenly because withdrawal can be dangerous.',image:img('1521791055366-0d553872125f6'),video:'https://www.youtube.com/results?search_query=quit+smoking+support',tags:['tobacco','alcohol']}
]},
{id:'back-pain',name:'Non-specific Low Back Pain',aliases:['lower back pain','backache','lumbar pain'],summary:'General self-care ideas for uncomplicated low back pain. Persistent or severe pain needs assessment.',caution:'Seek urgent medical care for new bladder/bowel problems, saddle numbness, major weakness, fever with severe back pain, or pain after major trauma.',items:[
{title:'Gentle mobility',category:'Exercise',description:'Keeping gently active is often preferable to prolonged bed rest for uncomplicated back pain.',how:'Try comfortable walking and gentle range-of-motion movements; increase activity gradually.',caution:'Avoid movements that clearly worsen pain. Get assessed if symptoms persist or progress.',image:img('1518611012118-696072aa579a'),video:'https://www.youtube.com/results?search_query=gentle+low+back+pain+mobility',tags:['mobility','walking']},
{title:'Beginner yoga',category:'Yoga',description:'Gentle yoga may help mobility and wellbeing when adapted to your symptoms.',how:'Choose a beginner routine and keep movements within a comfortable range.',caution:'Avoid forceful twisting or deep forward bending if these aggravate symptoms.',image:img('1599447421416-3414500d18a5'),video:'https://www.youtube.com/results?search_query=gentle+yoga+low+back+pain',tags:['gentle','flexibility']},
{title:'Anti-inflammatory style eating',category:'Diet',description:'A varied diet rich in vegetables, fruit, pulses, whole grains, nuts and healthy fats supports general health.',how:'Focus on overall dietary pattern rather than a single “healing” food.',caution:'No food or home remedy reliably cures back pain. Avoid expensive “detox” claims.',image:img('1540189549336-e6e99c3679fe'),video:'https://www.youtube.com/results?search_query=healthy+anti+inflammatory+diet',tags:['balanced','whole foods']},
{title:'Break up long sitting',category:'Habits',description:'Frequent position changes can make daily movement easier.',how:'Stand, walk briefly, or change position regularly rather than staying seated for long uninterrupted periods.',caution:'If sitting consistently triggers severe symptoms or leg weakness/numbness, seek assessment.',image:img('1517245386807-bb43f82c33c4'),video:'https://www.youtube.com/results?search_query=break+up+sitting+movement+tips',tags:['movement','ergonomics']}
]}
];
